# Generated by Django 2.1.7 on 2019-04-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='customTitle',
            field=models.TextField(default='CustomTitleText'),
            preserve_default=False,
        ),
    ]
