# Generated by Django 2.1.7 on 2019-04-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='showComments',
            field=models.BooleanField(default=False),
        ),
    ]
